# Base Image 
FROM colserra/neon_bot_docker

# 1. Setup home directory, non interactive shell and timezone
RUN mkdir -p /bot /neon && chmod 777 /bot
WORKDIR /bot
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Africa/Lagos
ENV TERM=xterm

RUN dnf -qq -y install gcc python3-devel

# 4. Copy files from repo to home directory
COPY . .

# 5. Install python3 requirements
RUN pip3 install -r requirements.txt

# 6. cleanup
RUN dnf -qq -y history undo last && dnf clean all

# 7. Start bot
CMD ["bash","run.sh"]
